export const reportData = [
  {
    name: "Saeed Al-Qahtani",
    procedure: "Surgery to remove a tumor in the lower jaw",
    date: "10-6-2024",
    cost: "2500$",
    reports: ["First report", "Second report", "Third report"],
    medicalRecordText: "Medical record",
    notesText: "Notes",
  },
  {
    name: "Fatima Al-Hasan",
    procedure: "Knee replacement surgery",
    date: "15-7-2024",
    cost: "3000$",
    reports: ["Initial report", "Follow-up", "Final assessment"],
    medicalRecordText: "Medical record",
    notesText: "Notes",
  },
  {
    name: "Omar Al-Zahrani",
    procedure: "Heart bypass surgery",
    date: "22-8-2024",
    cost: "4500$",
    reports: ["Pre-op evaluation", "Surgery report", "Recovery plan"],
    medicalRecordText: "Medical record",
    notesText: "Notes",
  },
  {
    name: "Aisha Al-Saud",
    procedure: "Appendectomy",
    date: "30-5-2024",
    cost: "1500$",
    reports: ["Emergency report", "Surgical notes", "Discharge summary"],
    medicalRecordText: "Medical record",
    notesText: "Notes",
  },
];